server:
  port : 8888
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:todoList
    username: jack
    password: jack
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true